# Generated by Django 5.1 on 2024-08-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=145),
        ),
        migrations.AddField(
            model_name='video',
            name='iframe',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='iframe2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=159),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('server1', 'Server1'), ('server2', 'Server2')], default='server1', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='url2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=10),
        ),
    ]
