# Generated by Django 5.1 on 2024-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_dislikes_video_iframe_video_iframe2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
