# Generated by Django 5.1 on 2024-08-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='position',
            field=models.CharField(blank=True, choices=[('bottom', 'Bottom'), ('top', 'Top'), ('center', 'Center')], max_length=10, null=True),
        ),
    ]
